//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public Carro()
        {
            this.Faturas = new HashSet<Fatura>();
        }
    
        public int Oid { get; set; }
        public string Placa { get; set; }
        public string Cor { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public int Ano { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Fatura> Faturas { get; set; }
    }
}
