//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oficinaContainer : DbContext
    {
        public oficinaContainer()
            : base("name=oficinaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Carro> Carros { get; set; }
        public virtual DbSet<Fatura> Faturas { get; set; }
        public virtual DbSet<Peca> Pecas { get; set; }
        public virtual DbSet<Atendimento> Atendimentoes { get; set; }
        public virtual DbSet<TipoPeca> TipoPecas { get; set; }
    }
}
