// <auto-generated />
namespace Oficina_codeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alteracaoAtendimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracaoAtendimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201806211205219_alteracaoAtendimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
